/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var wison = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,15],$V1=[1,24],$V2=[1,26],$V3=[1,25],$V4=[13,15],$V5=[2,8],$V6=[33,38,39,40],$V7=[19,43],$V8=[2,36],$V9=[1,50],$Va=[1,49],$Vb=[1,58],$Vc=[1,55],$Vd=[1,56],$Ve=[1,57],$Vf=[1,59],$Vg=[16,19,39,43],$Vh=[16,19,25,26,27,28,29],$Vi=[16,19,22,23,24,25,26,27,28,29];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"programa":3,"WISON":4,"ABRE_WISON":5,"bloque_lexico":6,"bloque_sintactico":7,"CIERRA_WISON":8,"EOF":9,"LEX":10,"ABRE_LEX":11,"lista_declaraciones_terminales":12,"CIERRA_LEX":13,"declaracion_terminal":14,"TERMINAL":15,"DOLLAR_ID":16,"FLECHA_LEX":17,"expresion_regular":18,"PUNTO_COMA":19,"elemento_con_operador":20,"elemento_base":21,"ASTERISCO":22,"MAS_OP":23,"INTERROGACION":24,"STRING":25,"RANGO_AZ":26,"RANGO_09":27,"PAREN_IZQ":28,"PAREN_DER":29,"SYNTAX":30,"ABRE_SYNTAX":31,"contenido_bloque_sintactico":32,"CIERRA_SYNTAX":33,"elemento_sintactico":34,"declaracion_no_terminal":35,"declaracion_simbolo_inicial":36,"produccion":37,"NO_TERMINAL":38,"PERCENT_ID":39,"INITIAL_SIM":40,"FLECHA_PROD":41,"cuerpo_produccion":42,"PIPE":43,"alternativa":44,"lista_simbolos":45,"simbolo":46,"$accept":0,"$end":1},
terminals_: {2:"error",4:"WISON",5:"ABRE_WISON",8:"CIERRA_WISON",9:"EOF",10:"LEX",11:"ABRE_LEX",13:"CIERRA_LEX",15:"TERMINAL",16:"DOLLAR_ID",17:"FLECHA_LEX",19:"PUNTO_COMA",22:"ASTERISCO",23:"MAS_OP",24:"INTERROGACION",25:"STRING",26:"RANGO_AZ",27:"RANGO_09",28:"PAREN_IZQ",29:"PAREN_DER",30:"SYNTAX",31:"ABRE_SYNTAX",33:"CIERRA_SYNTAX",38:"NO_TERMINAL",39:"PERCENT_ID",40:"INITIAL_SIM",41:"FLECHA_PROD",43:"PIPE"},
productions_: [0,[3,6],[3,6],[6,4],[6,3],[12,2],[12,1],[14,5],[14,3],[18,2],[18,1],[20,2],[20,2],[20,2],[20,1],[21,1],[21,1],[21,1],[21,1],[21,3],[7,4],[7,3],[32,2],[32,1],[34,1],[34,1],[34,1],[35,3],[35,3],[36,3],[36,3],[37,4],[37,3],[42,3],[42,1],[44,1],[44,0],[45,2],[45,1],[46,1],[46,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

            this.$ = {
                terminales: $$[$0-3],
                noTerminales: $$[$0-2].noTerminales,
                simboloInicial: $$[$0-2].simboloInicial,
                producciones: $$[$0-2].producciones,
                erroresLexicos: erroresLexicos,
                erroresSintacticos: erroresSintacticos
            };
            erroresLexicos = [];
            erroresSintacticos = [];
            return this.$;
        
break;
case 2:

                erroresSintacticos.push(
                    new ErrorWison(
                        'sintactico',
                        'Se esperaba "?Wison" para cerrar la estructura Wison.',
                        _$[$0-5].first_line
                    )
                );
            this.$ = {
                terminales: $$[$0-3],
                noTerminales: $$[$0-2].noTerminales,
                simboloInicial: $$[$0-2].simboloInicial,
                producciones: $$[$0-2].producciones,
                erroresLexicos: erroresLexicos,
                erroresSintacticos: erroresSintacticos
            };
            erroresLexicos = [];
            erroresSintacticos = [];
            return this.$;
        
break;
case 3: case 20: case 27: case 29:
 this.$ = $$[$0-1]; 
break;
case 4:
 this.$ = {}; 
break;
case 5:

            if ($$[$0]) { $$[$0-1][$$[$0].nombre] = $$[$0].expresion; }
            this.$ = $$[$0-1];
        
break;
case 6:

            this.$ = {};
            if ($$[$0]) { this.$[$$[$0].nombre] = $$[$0].expresion; }
        
break;
case 7:
 this.$ = { nombre: $$[$0-3], expresion: $$[$0-1] }; 
break;
case 8:

            erroresSintacticos.push(
                new ErrorWison(
                    'sintactico',
                    'Se esperaba un identificador de terminal ($_nombre) y una expresion despues de "Terminal".',
                    _$[$0-2].first_line
                )
            );
            this.$ = null;
        
break;
case 9:
 this.$ = { tipo: 'concatenacion', izq: $$[$0-1], der: $$[$0] }; 
break;
case 10: case 14: case 35: case 39: case 40:
 this.$ = $$[$0]; 
break;
case 11:
 this.$ = { tipo: 'kleene', expresion: $$[$0-1] }; 
break;
case 12:
 this.$ = { tipo: 'positiva', expresion: $$[$0-1] }; 
break;
case 13:
 this.$ = { tipo: 'opcional', expresion: $$[$0-1] }; 
break;
case 15:
 this.$ = { tipo: 'string', valor: $$[$0] }; 
break;
case 16:
 this.$ = { tipo: 'rango', valor: 'aA-zZ' }; 
break;
case 17:
 this.$ = { tipo: 'rango', valor: '0-9' }; 
break;
case 18:
 this.$ = { tipo: 'referencia', valor: $$[$0] }; 
break;
case 19:
 this.$ = { tipo: 'grupo', expresion: $$[$0-1] }; 
break;
case 21:
 this.$ = { noTerminales: [], simboloInicial: null, producciones: {} }; 
break;
case 22:

            if ($$[$0]) {
                if ($$[$0].tipo === 'no_terminal') $$[$0-1].noTerminales.push($$[$0].valor);
                else if ($$[$0].tipo === 'simbolo_inicial') $$[$0-1].simboloInicial = $$[$0].valor;
                else if ($$[$0].tipo === 'produccion') {
                    if (!$$[$0-1].producciones[$$[$0].nombre]) $$[$0-1].producciones[$$[$0].nombre] = [];
                    $$[$0-1].producciones[$$[$0].nombre] = $$[$0-1].producciones[$$[$0].nombre].concat($$[$0].alternativas);
                }
            }
            this.$ = $$[$0-1];
        
break;
case 23:

            this.$ = { noTerminales: [], simboloInicial: null, producciones: {} };
            if ($$[$0]) {
                if ($$[$0].tipo === 'no_terminal') this.$.noTerminales.push($$[$0].valor);
                else if ($$[$0].tipo === 'simbolo_inicial') this.$.simboloInicial = $$[$0].valor;
                else if ($$[$0].tipo === 'produccion') {
                    this.$.producciones[$$[$0].nombre] = $$[$0].alternativas;
                }
            }
        
break;
case 24:
 this.$ = $$[$0] ? { tipo: 'no_terminal', valor: $$[$0] } : null; 
break;
case 25:
 this.$ = $$[$0] ? { tipo: 'simbolo_inicial', valor: $$[$0] } : null; 
break;
case 26:
 this.$ = $$[$0] ? { tipo: 'produccion', nombre: $$[$0].nombre, alternativas: $$[$0].alternativas } : null; 
break;
case 28:

            erroresSintacticos.push(
                new ErrorWison(
                    'sintactico',
                    'Se esperaba un identificador de no terminal (%_nombre) despues de "No_Terminal".',
                    _$[$0-2].first_line
                )
            );
            this.$ = null;
        
break;
case 30:

                erroresSintacticos.push(
                    new ErrorWison(
                        'sintactico',
                        'Se esperaba un identificador de no terminal (%_nombre) despues de "Initial_Sim".',
                        _$[$0-2].first_line
                    )
                );
            this.$ = null;
        
break;
case 31:
 this.$ = { nombre: $$[$0-3], alternativas: $$[$0-1] }; 
break;
case 32:

                erroresSintacticos.push(
                    new ErrorWison(
                        'sintactico',
                        'Se esperaba "<=" seguido de una produccion valida para "' + $$[$0-2] + '".',
                        _$[$0-2].first_line
                    )
                );
            this.$ = null;
        
break;
case 33:
 $$[$0-2].push($$[$0]); this.$ = $$[$0-2]; 
break;
case 34: case 38:
 this.$ = [$$[$0]]; 
break;
case 36:
 this.$ = ['ε']; 
break;
case 37:
 $$[$0-1].push($$[$0]); this.$ = $$[$0-1]; 
break;
}
},
table: [{3:1,4:[1,2]},{1:[3]},{5:[1,3]},{6:4,10:[1,5]},{7:6,30:[1,7]},{11:[1,8]},{2:[1,10],8:[1,9]},{31:[1,11]},{12:12,13:[1,13],14:14,15:$V0},{9:[1,16]},{9:[1,17]},{32:18,33:[1,19],34:20,35:21,36:22,37:23,38:$V1,39:$V2,40:$V3},{13:[1,27],14:28,15:$V0},{30:[2,4]},o($V4,[2,6]),{2:[1,30],16:[1,29]},{1:[2,1]},{1:[2,2]},{33:[1,31],34:32,35:21,36:22,37:23,38:$V1,39:$V2,40:$V3},o($V5,[2,21]),o($V6,[2,23]),o($V6,[2,24]),o($V6,[2,25]),o($V6,[2,26]),{2:[1,34],39:[1,33]},{2:[1,36],39:[1,35]},{2:[1,38],41:[1,37]},{30:[2,3]},o($V4,[2,5]),{17:[1,39]},{19:[1,40]},o($V5,[2,20]),o($V6,[2,22]),{19:[1,41]},{19:[1,42]},{19:[1,43]},{19:[1,44]},o($V7,$V8,{42:45,44:46,45:47,46:48,16:$V9,39:$Va}),{19:[1,51]},{16:$Vb,18:52,20:53,21:54,25:$Vc,26:$Vd,27:$Ve,28:$Vf},o($V4,$V5),o($V6,[2,27]),o($V6,[2,28]),o($V6,[2,29]),o($V6,[2,30]),{19:[1,60],43:[1,61]},o($V7,[2,34]),o($V7,[2,35],{46:62,16:$V9,39:$Va}),o($Vg,[2,38]),o($Vg,[2,39]),o($Vg,[2,40]),o($V6,[2,32]),{16:$Vb,19:[1,63],20:64,21:54,25:$Vc,26:$Vd,27:$Ve,28:$Vf},o($Vh,[2,10]),o($Vh,[2,14],{22:[1,65],23:[1,66],24:[1,67]}),o($Vi,[2,15]),o($Vi,[2,16]),o($Vi,[2,17]),o($Vi,[2,18]),{16:$Vb,18:68,20:53,21:54,25:$Vc,26:$Vd,27:$Ve,28:$Vf},o($V6,[2,31]),o($V7,$V8,{45:47,46:48,44:69,16:$V9,39:$Va}),o($Vg,[2,37]),o($V4,[2,7]),o($Vh,[2,9]),o($Vh,[2,11]),o($Vh,[2,12]),o($Vh,[2,13]),{16:$Vb,20:64,21:54,25:$Vc,26:$Vd,27:$Ve,28:$Vf,29:[1,70]},o($V7,[2,33]),o($Vi,[2,19])],
defaultActions: {13:[2,4],16:[2,1],17:[2,2],27:[2,3]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse (input) {
    var self = this,
        stack = [0],
        tstack = [], // token stack
        vstack = [null], // semantic value stack
        lstack = [], // location stack
        table = this.table,
        yytext = '',
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;

    var args = lstack.slice.call(arguments, 1);

    //this.reductionCount = this.shiftCount = 0;

    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    // copy state
    for (var k in this.yy) {
      if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
        sharedState.yy[k] = this.yy[k];
      }
    }

    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);

    var ranges = lexer.options && lexer.options.ranges;

    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }

    function popStack (n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }

_token_stack:
    var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        // if token isn't its numeric value, convert
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }

    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        // retreive state number from top of stack
        state = stack[stack.length - 1];

        // use default actions if available
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            // read action for current state and first input
            action = table[state] && table[state][symbol];
        }

_handle_error:
        // handle parse error
        if (typeof action === 'undefined' || !action.length || !action[0]) {
            var error_rule_depth;
            var errStr = '';

            // Return the rule stack depth where the nearest error rule can be found.
            // Return FALSE when no error recovery rule was found.
            function locateNearestErrorRecoveryRule(state) {
                var stack_probe = stack.length - 1;
                var depth = 0;

                // try to recover from error
                for(;;) {
                    // check for error recovery rule in this state
                    if ((TERROR.toString()) in table[state]) {
                        return depth;
                    }
                    if (state === 0 || stack_probe < 2) {
                        return false; // No suitable error recovery rule available.
                    }
                    stack_probe -= 2; // popStack(1): [symbol, action]
                    state = stack[stack_probe];
                    ++depth;
                }
            }

            if (!recovering) {
                // first see if there's any chance at hitting an error recovery rule:
                error_rule_depth = locateNearestErrorRecoveryRule(state);

                // Report error
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push("'"+this.terminals_[p]+"'");
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line '+(yylineno+1)+":\n"+lexer.showPosition()+"\nExpecting "+expected.join(', ') + ", got '" + (this.terminals_[symbol] || symbol)+ "'";
                } else {
                    errStr = 'Parse error on line '+(yylineno+1)+": Unexpected " +
                                  (symbol == EOF ? "end of input" :
                                              ("'"+(this.terminals_[symbol] || symbol)+"'"));
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected,
                    recoverable: (error_rule_depth !== false)
                });
            } else if (preErrorSymbol !== EOF) {
                error_rule_depth = locateNearestErrorRecoveryRule(state);
            }

            // just recovered from another error
            if (recovering == 3) {
                if (symbol === EOF || preErrorSymbol === EOF) {
                    throw new Error(errStr || 'Parsing halted while starting to recover from another error.');
                }

                // discard current lookahead and grab another
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                symbol = lex();
            }

            // try to recover from error
            if (error_rule_depth === false) {
                throw new Error(errStr || 'Parsing halted. No suitable error recovery rule available.');
            }
            popStack(error_rule_depth);

            preErrorSymbol = (symbol == TERROR ? null : symbol); // save the lookahead token
            symbol = TERROR;         // insert generic error symbol as new lookahead
            state = stack[stack.length-1];
            action = table[state] && table[state][TERROR];
            recovering = 3; // allow 3 real symbols to be shifted before reporting a new error
        }

        // this shouldn't happen, unless resolve defaults are off
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: '+state+', token: '+symbol);
        }

        switch (action[0]) {
            case 1: // shift
                //this.shiftCount++;

                stack.push(symbol);
                vstack.push(lexer.yytext);
                lstack.push(lexer.yylloc);
                stack.push(action[1]); // push state
                symbol = null;
                if (!preErrorSymbol) { // normal execution/no error
                    yyleng = lexer.yyleng;
                    yytext = lexer.yytext;
                    yylineno = lexer.yylineno;
                    yyloc = lexer.yylloc;
                    if (recovering > 0) {
                        recovering--;
                    }
                } else {
                    // error just occurred, resume old lookahead f/ before error
                    symbol = preErrorSymbol;
                    preErrorSymbol = null;
                }
                break;

            case 2:
                // reduce
                //this.reductionCount++;

                len = this.productions_[action[1]][1];

                // perform semantic action
                yyval.$ = vstack[vstack.length-len]; // default to $$ = $1
                // default location, uses first token for firsts, last for lasts
                yyval._$ = {
                    first_line: lstack[lstack.length-(len||1)].first_line,
                    last_line: lstack[lstack.length-1].last_line,
                    first_column: lstack[lstack.length-(len||1)].first_column,
                    last_column: lstack[lstack.length-1].last_column
                };
                if (ranges) {
                  yyval._$.range = [lstack[lstack.length-(len||1)].range[0], lstack[lstack.length-1].range[1]];
                }
                r = this.performAction.apply(yyval, [yytext, yyleng, yylineno, sharedState.yy, action[1], vstack, lstack].concat(args));

                if (typeof r !== 'undefined') {
                    return r;
                }

                // pop off stack
                if (len) {
                    stack = stack.slice(0,-1*len*2);
                    vstack = vstack.slice(0, -1*len);
                    lstack = lstack.slice(0, -1*len);
                }

                stack.push(this.productions_[action[1]][0]);    // push nonterminal (reduce)
                vstack.push(yyval.$);
                lstack.push(yyval._$);
                // goto new state = table[STATE][NONTERMINAL]
                newState = table[stack[stack.length-2]][stack[stack.length-1]];
                stack.push(newState);
                break;

            case 3:
                // accept
                return true;
        }

    }

    return true;
}};

    var ErrorWison = require('../errores/ErrorWison'); 
    var erroresLexicos = [];
    var erroresSintacticos = [];
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* ignorar espacios, tabs, saltos de linea */
break;
case 1:/* comentario de linea */
break;
case 2:/* comentario de bloque */
break;
case 3:return 31;
break;
case 4:return 33;
break;
case 5:return 11;
break;
case 6:return 13;
break;
case 7:return 8;
break;
case 8:return 5;
break;
case 9:return 4;
break;
case 10:return 10;
break;
case 11:return 30;
break;
case 12:return 15;
break;
case 13:return 38;
break;
case 14:return 40;
break;
case 15:return 17;
break;
case 16:return 41;
break;
case 17:return 19;
break;
case 18:return 43;
break;
case 19:return 28;
break;
case 20:return 29;
break;
case 21:return 22;
break;
case 22:return 23;
break;
case 23:return 24;
break;
case 24:return 26;
break;
case 25:return 27;
break;
case 26:yy_.yytext = yy_.yytext.slice(1,-1); return 25;
break;
case 27:return 16;
break;
case 28:return 39;
break;
case 29:return 9;
break;
case 30:
                                        var linea = yy_.yylineno + 1;
                                        var ultimoError = erroresLexicos[erroresLexicos.length - 1];

                                        if (ultimoError && ultimoError.linea === linea && ultimoError._acumulando) {
                                            ultimoError._texto += yy_.yytext;
                                            ultimoError.mensaje = 'Texto no reconocido "' + ultimoError._texto + '"';
                                        } else {
                                            let nuevoError = new ErrorWison(
                                                'lexico',
                                                'Texto no reconocido "' + yy_.yytext + '"',
                                                linea
                                            );


                                            nuevoError._texto = yy_.yytext;
                                            nuevoError._acumulando = true;

                                            erroresLexicos.push(nuevoError);
                                        }
                                    
break;
}
},
rules: [/^(?:\s+)/,/^(?:#[^\n]*)/,/^(?:\/\*\*[\s\S]*?\*\/)/,/^(?:\{\{:)/,/^(?::\}\})/,/^(?:\{:)/,/^(?::\})/,/^(?:\?Wison\b)/,/^(?:¿)/,/^(?:Wison\b)/,/^(?:Lex\b)/,/^(?:Syntax\b)/,/^(?:Terminal\b)/,/^(?:No_Terminal\b)/,/^(?:Initial_Sim\b)/,/^(?:<-)/,/^(?:<=)/,/^(?:;)/,/^(?:\|)/,/^(?:\()/,/^(?:\))/,/^(?:\*)/,/^(?:\+)/,/^(?:\?)/,/^(?:\[aA-zZ\])/,/^(?:\[0-9\])/,/^(?:'[^']+')/,/^(?:\$_[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:%_[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = wison;
exports.Parser = wison.Parser;
exports.parse = function () { return wison.parse.apply(wison, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}